const extensionToLanguage: Record<string, string> = {
	ts: "typescript",
	tsx: "typescript",
	js: "javascript",
	jsx: "javascript",
	mjs: "javascript",
	cjs: "javascript",
	json: "json",
	html: "html",
	htm: "html",
	css: "css",
	scss: "scss",
	less: "less",
	md: "markdown",
	mdx: "markdown",
	py: "python",
	pyw: "python",
	rs: "rust",
	c: "cpp",
	cpp: "cpp",
	cc: "cpp",
	cxx: "cpp",
	h: "cpp",
	hpp: "cpp",
	hxx: "cpp",
	java: "java",
	xml: "xml",
	svg: "xml",
	yaml: "yaml",
	yml: "yaml",
	toml: "ini",
	sh: "shell",
	bash: "shell",
	zsh: "shell",
	sql: "sql",
	go: "go",
	rb: "ruby",
	php: "php",
	swift: "swift",
	kt: "kotlin",
	lua: "lua",
	r: "r",
	dockerfile: "dockerfile",
	cls: "apex",
	trigger: "apex",
	apex: "apex",
	astro: "astro",
	page: "html",
	component: "html",
};

export function getLanguage(extension: string | null): string | null {
	if (!extension) return null;
	return extensionToLanguage[extension.toLowerCase()] ?? null;
}
